spring:
  config:
    activate:
      on-profile: dev
  datasource:
    hikari:
      username: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/shop?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      password: Ymg4798!@#
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        format_sql: 'true'
    defer-datasource-initialization: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: never
      encoding: UTF-8
  devtools:
    remote:
      restart:
        enabled: 'false'
    livereload:
      enabled: 'true'
  mustache:
    cache: 'false'
logging:
  level:
    root: info

---

spring:
  config:
    activate:
      on-profile: test
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:shop;MODE=Mysql
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        format_sql: 'true'
    defer-datasource-initialization: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  sql:
    init:
      encoding: UTF-8

  devtools:
    remote:
      restart:
        enabled: 'false'
    livereload:
      enabled: 'true'
  mustache:
    cache: 'false'

logging:
  level:
    root: info
